ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

ARG SERVICE_NAME

WORKDIR /${SERVICE_NAME}

# -- install 3rd-party

ARG TARGETOS TARGETARCH

# air
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH go install github.com/cosmtrek/air@latest

RUN apt-get update && apt-get install -y \
    gcc \
    make \
    gettext \
    jq \
    && rm -rf /var/lib/apt/lists/*

ARG KRAKEND_CE_VERSION
RUN git clone -b v${KRAKEND_CE_VERSION} https://github.com/krakendio/krakend-ce.git /krakend && cd /krakend && make build && cp krakend /usr/bin

# -- set up Go
RUN chown -R nobody:nogroup /go
ENV GOCACHE /go/.cache/go-build
ENV GOENV /go/.config/go/env

USER nobody

ENTRYPOINT ["tail", "-f", "/dev/null"]
