ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

USER root

RUN apt-get update && \
    apt-get install -y gcc make gettext jq \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/krakendio/krakend-ce.git /krakend

WORKDIR /krakend

ARG KRAKEND_CE_VERSION
RUN git checkout v${KRAKEND_CE_VERSION}

RUN make build

RUN cp krakend /usr/bin/krakend

ARG SERVICE_NAME
WORKDIR /${SERVICE_NAME}

COPY . .

RUN go install github.com/cosmtrek/air@latest

# Install local TLS files
ARG TARGETARCH
RUN curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/$TARGETARCH" && \
    chmod +x mkcert-v*-linux-$TARGETARCH && \
    cp mkcert-v*-linux-$TARGETARCH /usr/local/bin/mkcert
RUN mkcert -install && mkdir cert && mkcert -client -key-file /etc/ssl/dev-key.pem -cert-file /etc/ssl/dev-cert.pem localhost api-gateway

# Initialise krakend.json
RUN make config

ENTRYPOINT ["tail", "-f", "/dev/null"]
