ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

USER root

RUN apt-get update && \
    apt-get install -y gcc make gettext jq \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/krakendio/krakend-ce.git /krakend

WORKDIR /krakend

ARG KRAKEND_VERSION
RUN git checkout v${KRAKEND_VERSION}

RUN make build

RUN cp krakend /usr/bin/krakend

ARG SERVICE_NAME
WORKDIR /${SERVICE_NAME}

COPY . .

RUN go install github.com/cosmtrek/air@latest

ENTRYPOINT ["tail", "-f", "/dev/null"]
