name: Coverage

on: [push, pull_request]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env          

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Generate coverage report
        run: |
          cd multi_auth_plugin
          go mod tidy
          go test -race ./... -coverprofile=coverage_multi_auth_plugin.txt -covermode=atomic

      - name: Generate coverage report
        run: |
          cd grpc_proxy_plugin
          go mod tidy
          go test -race ./... -coverprofile=coverage_grpc_proxy_plugin.txt -covermode=atomic

      - name: Upload coverage report (multi_auth_plugin)
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage_multi_auth_plugin.txt
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage report (grpc_proxy_plugin)
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage_grpc_proxy_plugin.txt
          flags: unittests
          name: codecov-umbrella
