name: Coverage

on: [push, pull_request]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - uses: actions/setup-go@v3
        with:
          go-version: 1.24.2

      - name: Generate coverage report (multi-auth)
        run: |
          cd plugins/multi-auth
          go mod tidy
          go test -race ./... -coverprofile=coverage-multi-auth-plugin.txt -covermode=atomic

      - name: Generate coverage report (grpc-proxy)
        run: |
          cd plugins/grpc-proxy
          go mod tidy
          go test -race ./... -coverprofile=coverage-grpc-proxy-plugin.txt -covermode=atomic

      - name: Generate coverage report (registry)
        run: |
          cd plugins/registry
          go mod tidy
          go test -race ./... -coverprofile=coverage-registry-plugin.txt -covermode=atomic
      - name: Generate coverage report (blob)
        run: |
          cd plugins/blob
          go mod tidy
          go test -race ./... -coverprofile=coverage-blob-plugin.txt -covermode=atomic

      - name: Upload coverage report (multi-auth)
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage-multi-auth-plugin.txt
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage report (grpc-proxy)
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage-grpc-proxy-plugin.txt
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage report (registry)
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage-registry-plugin.txt
          flags: unittests
          name: codecov-umbrella

      - name: Upload coverage report (blob)
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage-blob-plugin.txt
          flags: unittests
          name: codecov-umbrella
