name: Coverage

on: [push, pull_request]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v2

      - name: Generate coverage report
        run: |
          cd plugin
          go mod tidy
          go test -race ./... -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
