name: Build and Push Images

on:
  workflow_call:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
    tags:
      - "*-rc"
  release:
    types: [published]

jobs:
  docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.botGitHubToken }}

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: drop@instill-ai.com
          password: ${{ secrets.botDockerHubPassword }}

      - name: Set short commit SHA
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push (commit hash and latest)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          build-args: |
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            SERVICE_VERSION=${{ env.COMMIT_SHORT_SHA }}
            GOLANG_VERSION=${{ env.GOLANG_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            KRAKEND_CE_VERSION=${{ env.KRAKEND_CE_VERSION }}
          tags: |
            instill/api-gateway:${{ env.COMMIT_SHORT_SHA }}
            instill/api-gateway:latest
          cache-from: type=registry,ref=instill/api-gateway:buildcache
          cache-to: type=registry,ref=instill/api-gateway:buildcache,mode=max

      - name: Set Versions
        if: github.event_name == 'release' || startsWith(github.ref, 'refs/tags/')
        uses: actions/github-script@v6
        id: set_version
        with:
          script: |
            const tag = '${{ github.ref_name }}'
            const no_v_tag = tag.replace('v', '')
            core.setOutput('tag', tag)
            core.setOutput('no_v_tag', no_v_tag)

      - name: Build and push (rc/release)
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          build-args: |
            SERVICE_NAME=${{ env.SERVICE_NAME }}
            SERVICE_VERSION=${{steps.set_version.outputs.no_v_tag}}
            GOLANG_VERSION=${{ env.GOLANG_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
            KRAKEND_CE_VERSION=${{ env.KRAKEND_CE_VERSION }}
          tags: instill/api-gateway:${{steps.set_version.outputs.no_v_tag}}
          cache-from: type=registry,ref=instill/api-gateway:buildcache
          cache-to: type=registry,ref=instill/api-gateway:buildcache,mode=max
